import { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext(null);

const translations = {
  en: {
    dashboard: "Dashboard",
    customers: "Customers",
    profile: "Profile",
    voiceEntry: "Voice Entry",
    addCustomer: "Add Customer",
    netOutstanding: "Net Outstanding Balance",
    outstandingCredit: "Outstanding Credit",
    paymentsReceived: "Payments Received",
    recentTransactions: "Recent Transactions",
    voiceSearch: "Voice Search",
    searchPlaceholder: "Search customers...",
    amount: "Amount",
    type: "Type",
    description: "Description",
    creditUdhaar: "Credit (Udhaar)",
    paymentJama: "Payment (Jama)",
    save: "Save",
    cancel: "Cancel",
    downloadPdf: "Download PDF",
    sendWhatsapp: "Send WhatsApp",
    ledgerBook: "Ledger Book",
    logout: "Logout",
    settings: "Settings",
    newTransaction: "New Entry",
    businessName: "Business Name",
    proprietor: "Proprietor",
    phone: "Phone",
    email: "Email",
    address: "Address",
    saveChanges: "Save Changes",
    noTransactions: "No transactions recorded yet.",
    noCustomers: "No customers in your ledger.",
    billingHistory: "Billing History",
    statementPeriod: "Statement Period",
    generateStatement: "Generate Statement",
    voiceAssistant: "Voice Assistant",
    language: "Language",
    todaysCredit: "Today's Credit",
    todaysPayments: "Today's Payments",
    activeCustomers: "Active Customers",
    quickActions: "Quick Actions",
    addTransactionVoice: "Add Transaction using Voice",
  },
  hi: {
    dashboard: "डैशबोर्ड",
    customers: "ग्राहक सूची",
    profile: "प्रोफ़ाइल",
    voiceEntry: "आवाज़ प्रविष्टि",
    addCustomer: "ग्राहक जोड़ें",
    netOutstanding: "कुल बकाया राशि",
    outstandingCredit: "कुल उधार",
    paymentsReceived: "कुल भुगतान मिला",
    recentTransactions: "हाल के लेन-देन",
    voiceSearch: "आवाज़ से खोजें",
    searchPlaceholder: "ग्राहक खोजें...",
    amount: "रकम",
    type: "प्रकार",
    description: "विवरण",
    creditUdhaar: "उधार दिया (Credit)",
    paymentJama: "जमा मिला (Payment)",
    save: "सुरक्षित करें",
    cancel: "रद्द करें",
    downloadPdf: "पीडीएफ डाउनलोड",
    sendWhatsapp: "व्हाट्सएप भेजें",
    ledgerBook: "खाता बही",
    logout: "लॉगआउट",
    settings: "सेटिंग्स",
    newTransaction: "नयी एंट्री",
    businessName: "व्यापार का नाम",
    proprietor: "मालिक का नाम",
    phone: "फ़ोन",
    email: "ईमेल",
    address: "पता",
    saveChanges: "बदलाव सहेजें",
    noTransactions: "अभी तक कोई लेन-देन दर्ज नहीं है।",
    noCustomers: "खाते में कोई ग्राहक नहीं है।",
    billingHistory: "बिल इतिहास",
    statementPeriod: "विवरण अवधि",
    generateStatement: "रिपोर्ट बनाएं",
    voiceAssistant: "आवाज़ सहायक",
    language: "भाषा",
    todaysCredit: "आज का उधार",
    todaysPayments: "आज का भुगतान",
    activeCustomers: "सक्रिय ग्राहक",
    quickActions: "त्वरित कार्रवाई",
    addTransactionVoice: "बोलकर लेन-देन जोड़ें",
  },
  hinglish: {
    dashboard: "Dashboard",
    customers: "Customers List",
    profile: "My Profile",
    voiceEntry: "Voice Entry",
    addCustomer: "Naya Customer Jodein",
    netOutstanding: "Total Bakaya Balance",
    outstandingCredit: "Total Udhaar Diya",
    paymentsReceived: "Total Jama Mila",
    recentTransactions: "Haal Ke Transactions",
    voiceSearch: "Voice Se Khojein",
    searchPlaceholder: "Customer search karein...",
    amount: "Amount / Paisa",
    type: "Transaction Type",
    description: "Description / Detailing",
    creditUdhaar: "Udhaar Diya (Credit)",
    paymentJama: "Jama Mila (Payment)",
    save: "Save Karein",
    cancel: "Cancel Karein",
    downloadPdf: "Download PDF",
    sendWhatsapp: "WhatsApp Bhejein",
    ledgerBook: "Khata Bahi Book",
    logout: "Log Out",
    settings: "Settings",
    newTransaction: "Nayi Entry",
    businessName: "Business Ka Naam",
    proprietor: "Maalik Ka Naam",
    phone: "Phone Number",
    email: "Email Address",
    address: "Address / Pata",
    saveChanges: "Save Changes",
    noTransactions: "Abhi koi transaction nahi hai.",
    noCustomers: "Khate me koi customer nahi hai.",
    billingHistory: "Bill History",
    statementPeriod: "Statement Ka Time",
    generateStatement: "Report Banayein",
    voiceAssistant: "Voice Assistant",
    language: "Bhasha (Language)",
    todaysCredit: "Aaj Ka Udhaar",
    todaysPayments: "Aaj Ka Payment",
    activeCustomers: "Active Customers",
    quickActions: "Quick Actions",
    addTransactionVoice: "Bolkar transaction jodein",
  },
  mr: {
    dashboard: "डॅशबोर्ड",
    customers: "ग्राहक",
    profile: "प्रोफाइल",
    voiceEntry: "आवाज नोंदणी",
    addCustomer: "ग्राहक जोडा",
    netOutstanding: "एकूण थकीत रक्कम",
    outstandingCredit: "एकूण उधार",
    paymentsReceived: "एकूण जमा रक्कम",
    recentTransactions: "अलीकडील व्यवहार",
    voiceSearch: "आवाजाने शोधा",
    searchPlaceholder: "ग्राहक शोधा...",
    amount: "रक्कम",
    type: "प्रकार",
    description: "तपशील",
    creditUdhaar: "उधार दिले (Credit)",
    paymentJama: "जमा मिळाले (Payment)",
    save: "जतन करा",
    cancel: "रद्द करा",
    downloadPdf: "पीडीएफ डाउनलोड",
    sendWhatsapp: "व्हाट्सएप पाठवा",
    ledgerBook: "खाते वही",
    logout: "लॉगआउट",
    settings: "सेटिंग्ज",
    newTransaction: "नवीन व्यवहार",
    businessName: "व्यवसायाचे नाव",
    proprietor: "मालकाचे नाव",
    phone: "फोन",
    email: "ईमेल",
    address: "पत्ता",
    saveChanges: "बदल जतन करा",
    noTransactions: "अद्याप कोणतेही व्यवहार नाहीत.",
    noCustomers: "खात्यात कोणतेही ग्राहक नाहीत.",
    billingHistory: "बिल इतिहास",
    statementPeriod: "अहवाल कालावधी",
    generateStatement: "अहवाल तयार करा",
    voiceAssistant: "आवाज सहाय्यक",
    language: "भाषा",
    todaysCredit: "आजचे उधार",
    todaysPayments: "आजचे पेमेंट",
    activeCustomers: "सक्रिय ग्राहक",
    quickActions: "द्रुत कृती",
    addTransactionVoice: "बोलून व्यवहार जोडा",
  },
  gu: {
    dashboard: "ડેશબોર્ડ",
    customers: "ગ્રાહકો",
    profile: "પ્રોફાઇલ",
    voiceEntry: "અવાજ નોંધણી",
    addCustomer: "ગ્રાહક ઉમેરો",
    netOutstanding: "કુલ બાકી રકમ",
    outstandingCredit: "કુલ ઉધાર",
    paymentsReceived: "કુલ જમા રકમ",
    recentTransactions: "તાજેતરના વ્યવહારો",
    voiceSearch: "અવાજથી શોધો",
    searchPlaceholder: "ગ્રાહક શોધો...",
    amount: "રકમ",
    type: "પ્રકાર",
    description: "વિગત",
    creditUdhaar: "ઉધાર આપ્યું (Credit)",
    paymentJama: "જમા મળ્યું (Payment)",
    save: "સાચવો",
    cancel: "રદ કરો",
    downloadPdf: "પીડીએફ ડાઉનલોડ",
    sendWhatsapp: "વોટ્સએપ મોકલો",
    ledgerBook: "ખાતા વહી",
    logout: "લોગઆઉટ",
    settings: "સેટિંગ્સ",
    newTransaction: "નવો વ્યવહાર",
    businessName: "વ્યવસાયનું નામ",
    proprietor: "માલિકનું નામ",
    phone: "ફોન",
    email: "ઇમેઇલ",
    address: "સરનામું",
    saveChanges: "ફેરફારો સાચવો",
    noTransactions: "હજુ સુધી કોઈ વ્યવહાર નથી.",
    noCustomers: "ખાતામાં કોઈ ગ્રાહકો નથી.",
    billingHistory: "બિલ ઇતિહાસ",
    statementPeriod: "અહેવાલ સમયગાળો",
    generateStatement: "અહેવાલ બનાવો",
    voiceAssistant: "અવાજ સહાયક",
    language: "ભાષા",
    todaysCredit: "આજનું ઉધાર",
    todaysPayments: "આજની ચુકવણી",
    activeCustomers: "સક્રિય ગ્રાહકો",
    quickActions: "ઝડપી ક્રિયાઓ",
    addTransactionVoice: "બોલીને વ્યવહાર ઉમેરો",
  },
  ta: {
    dashboard: "டாஷ்போர்டு",
    customers: "வாடிக்கையாளர்கள்",
    profile: "சுயவிவரம்",
    voiceEntry: "குரல் பதிவு",
    addCustomer: "வாடிக்கையாளர் சேர்",
    netOutstanding: "மொத்த நிலுவைத் தொகை",
    outstandingCredit: "மொத்த கடன்",
    paymentsReceived: "பெறப்பட்ட தொகை",
    recentTransactions: "சமீபத்திய பரிவர்த்தனைகள்",
    voiceSearch: "குரல் வழி தேடல்",
    searchPlaceholder: "தேடுக...",
    amount: "தொகை",
    type: "வகை",
    description: "விவரம்",
    creditUdhaar: "கடன் கொடுத்தது (Credit)",
    paymentJama: "பணம் பெற்றது (Payment)",
    save: "சேமி",
    cancel: "ரத்து செய்",
    downloadPdf: "PDF பதிவிறக்கு",
    sendWhatsapp: "வாட்ஸ்அப் அனுப்பு",
    ledgerBook: "கணக்கு புத்தகம்",
    logout: "வெளியேறு",
    settings: "அமைப்புகள்",
    newTransaction: "புதிய பதிவு",
    businessName: "வணிகப் பெயர்",
    proprietor: "உரிமையாளர் பெயர்",
    phone: "தொலைபேசி",
    email: "மின்னஞ்சல்",
    address: "முகவரி",
    saveChanges: "மாற்றங்களைச் சேமி",
    noTransactions: "பரிவர்த்தனைகள் எதுவும் இல்லை.",
    noCustomers: "வாடிக்கையாளர்கள் யாரும் இல்லை.",
    billingHistory: "பில் வரலாறு",
    statementPeriod: "அறிக்கை காலம்",
    generateStatement: "அறிக்கை உருவாக்கு",
    voiceAssistant: "குரல் உதவியாளர்",
    language: "மொழி",
    todaysCredit: "இன்றைய கடன்",
    todaysPayments: "இன்றைய கட்டணம்",
    activeCustomers: "செயலில் உள்ள வாடிக்கையாளர்கள்",
    quickActions: "விரைவான செயல்கள்",
    addTransactionVoice: "பேசி பரிவர்த்தனை சேர்",
  },
  te: {
    dashboard: "డ్యాష్‌బోర్డ్",
    customers: "ఖాతాదారులు",
    profile: "ప్రొఫైల్",
    voiceEntry: "వాయిస్ ఎంట్రీ",
    addCustomer: "ఖాతาదారుని చేర్చు",
    netOutstanding: "మొత్తం బకాయి",
    outstandingCredit: "మొత్తం అప్పు",
    paymentsReceived: "మొత్తం వసూలు",
    recentTransactions: "ఇటీవలి లావాదేవీలు",
    voiceSearch: "వాయిస్ శోధన",
    searchPlaceholder: "ఖాతాదారుని వెతకండి...",
    amount: "మొత్తం",
    type: "రకం",
    description: "వివరణ",
    creditUdhaar: "అప్పు ఇచ్చాను (Credit)",
    paymentJama: "వసూలు అయింది (Payment)",
    save: "సేవ్ చేయి",
    cancel: "రద్దు చేయి",
    downloadPdf: "PDF డౌన్‌లోడ్",
    sendWhatsapp: "వాట్సాప్ చేయి",
    ledgerBook: "ఖాతా పుస్తకం",
    logout: "లాగ్ అవుట్",
    settings: "సెట్టింగులు",
    newTransaction: "కొత్త ఎంట్రీ",
    businessName: "వ్యాపార నామం",
    proprietor: "యజమాని పేరు",
    phone: "ఫోన్",
    email: "ఈమెయిల్",
    address: "చిరునామా",
    saveChanges: "మార్పులను సేవ్ చేయి",
    noTransactions: "ఇంకా లావాదేవీలు లేవు.",
    noCustomers: "ఖాతాలో కస్టమర్లు లేరు.",
    billingHistory: "బిల్లు చరిత్ర",
    statementPeriod: "నివేదిక కాలం",
    generateStatement: "నివేదిక తయారుచేయి",
    voiceAssistant: "వాయిస్ అసిస్టెంట్",
    language: "భాష",
    todaysCredit: "ఈరోజు అప్పు",
    todaysPayments: "ఈరోజు వసూళ్లు",
    activeCustomers: "క్రియాశీల కస్టమర్లు",
    quickActions: "త్వరిత చర్యలు",
    addTransactionVoice: "వాయిస్ ద్వారా ఎంట్రీ చేయండి",
  },
  bn: {
    dashboard: "ড্যাশবোর্ড",
    customers: "গ্রাহক তালিকা",
    profile: "প্রোফাইল",
    voiceEntry: "ভয়েস এন্ট্রি",
    addCustomer: "গ্রাহক যোগ করুন",
    netOutstanding: "মোট বকেয়া ব্যালেন্স",
    outstandingCredit: "মোট ধার দেওয়া",
    paymentsReceived: "মোট জমা পাওয়া",
    recentTransactions: "সাম্প্রতিক লেনদেন",
    voiceSearch: "ভয়েস অনুসন্ধান",
    searchPlaceholder: "গ্রাহক খুঁজুন...",
    amount: "পরিমাণ",
    type: "প্রকার",
    description: "বিবরণ",
    creditUdhaar: "ধার দেওয়া (Credit)",
    paymentJama: "জমা পাওয়া (Payment)",
    save: "সংরক্ষণ করুন",
    cancel: "বাতিল করুন",
    downloadPdf: "পিডিএফ ডাউনলোড",
    sendWhatsapp: "হোয়াটসঅ্যাপ পাঠান",
    ledgerBook: "খাতা বই",
    logout: "লগ আউট",
    settings: "সেটিংস",
    newTransaction: "নতুন এন্ট্রি",
    businessName: "ব্যবসার নাম",
    proprietor: "মালিকের নাম",
    phone: "ফোন",
    email: "ইমেল",
    address: "ঠিকানা",
    saveChanges: "পরিবর্তন সংরক্ষণ করুন",
    noTransactions: "কোনো লেনদেন নথিভুক্ত নেই।",
    noCustomers: "খাতায় কোনো গ্রাহক নেই।",
    billingHistory: "বিল ইতিহাস",
    statementPeriod: "রিপোর্ট সময়কাল",
    generateStatement: "রিপোর্ট তৈরি করুন",
    voiceAssistant: "ভয়েস অ্যাসিস্ট্যান্ট",
    language: "ভাষা",
    todaysCredit: "আজকের ধার",
    todaysPayments: "আজকের পেমেন্ট",
    activeCustomers: "সক্রিয় গ্রাহক",
    quickActions: "দ্রুত লিংক",
    addTransactionVoice: "কথা বলে লেনদেন যোগ করুন",
  },
  pa: {
    dashboard: "ਡੈਸ਼ਬੋਰਡ",
    customers: "ਗਾਹਕ ਸੂਚੀ",
    profile: "ਪ੍ਰੋਫਾਈਲ",
    voiceEntry: "ਆਵਾਜ਼ ਐਂਟਰੀ",
    addCustomer: "ਗਾਹਕ ਜੋੜੋ",
    netOutstanding: "ਕੁੱਲ ਬਕਾਇਆ",
    outstandingCredit: "ਕੁੱਲ ਉਧਾਰ ਦਿੱਤਾ",
    paymentsReceived: "ਕੁੱਲ ਜਮ੍ਹਾ ਮਿਲਿਆ",
    recentTransactions: "ਹਾਲੀਆ ਲੈਣ-ਦੇਣ",
    voiceSearch: "ਆਵਾਜ਼ ਨਾਲ ਖੋਜੋ",
    searchPlaceholder: "ਗਾਹਕ ਖੋਜੋ...",
    amount: "ਰਕਮ",
    type: "ਕਿਸਮ",
    description: "ਵੇਰਵਾ",
    creditUdhaar: "ਉਧਾਰ ਦਿੱਤਾ (Credit)",
    paymentJama: "ਜਮ੍ਹਾ ਮਿਲਿਆ (Payment)",
    save: "ਸੁਰੱਖਿਅਤ ਕਰੋ",
    cancel: "ਰੱਦ ਕਰੋ",
    downloadPdf: "ਪੀਡੀਐਫ ਡਾਊਨਲੋਡ",
    sendWhatsapp: "ਵਟਸਐਪ ਭੇਜੋ",
    ledgerBook: "ਖਾਤਾ ਵਹੀ",
    logout: "ਲੌਗਆਊਟ",
    settings: "ਸੈਟਿੰਗਾਂ",
    newTransaction: "ਨਵੀਂ ਐਂਟਰੀ",
    businessName: "ਵਪਾਰ ਦਾ ਨਾਮ",
    proprietor: "ਮਾਲਕ ਦਾ ਨਾਮ",
    phone: "ਫ਼ੋਨ",
    email: "ਈਮੇਲ",
    address: "ਪਤਾ",
    saveChanges: "ਤਬਦੀਲੀਆਂ ਸੁਰੱਖਿਅਤ ਕਰੋ",
    noTransactions: "ਕੋਈ ਲੈਣ-ਦੇਣ ਦਰਜ ਨਹੀਂ ਹੈ।",
    noCustomers: "ਖਾਤੇ ਵਿੱਚ ਕੋਈ ਗਾਹਕ ਨਹੀਂ ਹੈ।",
    billingHistory: "ਬਿੱਲ ਇਤਿਹਾਸ",
    statementPeriod: "ਰਿਪੋਰਟ ਦੀ ਮਿਆਦ",
    generateStatement: "ਰਿਪੋਰਟ ਬਣਾਓ",
    voiceAssistant: "ਆਵਾਜ਼ ਸਹਾਇਕ",
    language: "ਭਾਸ਼ਾ",
    todaysCredit: "ਅੱਜ ਦਾ ਉਧਾਰ",
    todaysPayments: "ਅੱਜ ਦੀ ਅਦਾਇਗੀ",
    activeCustomers: "ਸਰਗਰਮ ਗਾਹਕ",
    quickActions: "ਤੁਰੰਤ ਕਾਰਵਾਈ",
    addTransactionVoice: "ਬੋਲ ਕੇ ਲੈਣ-ਦੇਣ ਜੋੜੋ",
  }
};

export const languagesList = [
  { code: 'en', name: 'English' },
  { code: 'hi', name: 'हिन्दी (Hindi)' },
  { code: 'hinglish', name: 'Hinglish' },
  { code: 'mr', name: 'मराठी (Marathi)' },
  { code: 'gu', name: 'ગુજરાતી (Gujarati)' },
  { code: 'ta', name: 'தமிழ் (Tamil)' },
  { code: 'te', name: 'తెలుగు (Telugu)' },
  { code: 'bn', name: 'বাংলা (Bengali)' },
  { code: 'pa', name: 'ਪੰਜਾਬੀ (Punjabi)' }
];

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState(() => {
    return localStorage.getItem('credlink_language') || 'en';
  });

  const setLanguage = (lang) => {
    localStorage.setItem('credlink_language', lang);
    setLanguageState(lang);
  };

  const t = (key) => {
    const langDict = translations[language] || translations['en'];
    return langDict[key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useTranslation() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useTranslation must be used within a LanguageProvider');
  }
  return context;
}
