const fs = require('fs');
const path = require('path');
const PDFDocument = require('pdfkit');

const BILLS_DIR = path.join(__dirname, '..', '..', 'generated', 'bills');
if (!fs.existsSync(BILLS_DIR)) fs.mkdirSync(BILLS_DIR, { recursive: true });

function formatINR(amount) {
  const n = Number(amount) || 0;
  return '₹' + n.toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
}

function formatDate(date) {
  return new Date(date).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' });
}

function formatTime(date) {
  return new Date(date).toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit' });
}

function drawHeader(doc, subtitle) {
  doc
    .fillColor('#2563eb')
    .fontSize(24)
    .font('Helvetica-Bold')
    .text('CREDLINK', { align: 'center' });
  doc
    .fillColor('#555')
    .fontSize(11)
    .font('Helvetica')
    .text('Digital Credit Ledger', { align: 'center' });
  doc.moveDown(0.3);
  if (subtitle) {
    doc.fontSize(13).fillColor('#111').font('Helvetica-Bold').text(subtitle, { align: 'center' });
  }
  doc.moveDown(0.5);
  doc
    .strokeColor('#2563eb')
    .lineWidth(2)
    .moveTo(50, doc.y)
    .lineTo(doc.page.width - 50, doc.y)
    .stroke();
  doc.moveDown(0.8);
}

function drawFooter(doc) {
  const bottom = doc.page.height - 70;
  doc
    .fontSize(9)
    .fillColor('#888')
    .font('Helvetica-Oblique')
    .text('Generated by CredLink — Digital Credit Ledger', 50, bottom, {
      align: 'center',
      width: doc.page.width - 100,
    })
    .text('Please verify the transaction details.', 50, bottom + 12, {
      align: 'center',
      width: doc.page.width - 100,
    });
}

function drawInfoRow(doc, label, value) {
  doc.font('Helvetica-Bold').fontSize(10).fillColor('#333').text(label, { continued: true });
  doc.font('Helvetica').fillColor('#111').text('  ' + (value || '-'));
}

/**
 * Generates an official, highly polished single-transaction receipt PDF.
 * Saves it under server/generated/bills/. Returns the absolute file path.
 */
async function generateTransactionPDF({ merchant, customer, transaction }) {
  const fileName = `${transaction.receiptNumber}.pdf`;
  const filePath = path.join(BILLS_DIR, fileName);

  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 50 });
    const stream = fs.createWriteStream(filePath);
    doc.pipe(stream);

    // 1. Draw top official title header
    doc.rect(50, 45, doc.page.width - 100, 30).fill('#2563eb');
    doc.fillColor('#fff').font('Helvetica-Bold').fontSize(12).text('TAX INVOICE / TRANSACTION RECEIPT', 60, 54);
    
    // 2. Merchant Info & Invoice Metadata side-by-side
    doc.y = 90;
    const topY = doc.y;
    doc.font('Helvetica-Bold').fontSize(14).fillColor('#1e293b').text(merchant.businessName || 'My Kirana Store', 50, topY);
    doc.font('Helvetica').fontSize(9).fillColor('#64748b');
    doc.text(`Proprietor: ${merchant.name}`, 50, doc.y + 3);
    doc.text(`Email: ${merchant.email}`, 50, doc.y + 2);
    if (merchant.phone) {
      doc.text(`Phone: ${merchant.phone}`, 50, doc.y + 2);
    }

    // Right Column: Metadata
    const rightX = 350;
    doc.font('Helvetica-Bold').fontSize(10).fillColor('#1e293b').text('INVOICE DETAILS', rightX, topY);
    doc.font('Helvetica').fontSize(9).fillColor('#475569');
    doc.text(`Receipt No: ${transaction.receiptNumber}`, rightX, doc.y + 4);
    doc.text(`Date: ${formatDate(transaction.createdAt)}`, rightX, doc.y + 2);
    doc.text(`Time: ${formatTime(transaction.createdAt)}`, rightX, doc.y + 2);

    // Divider Line
    doc.moveDown(2);
    const billToY = doc.y;
    doc.strokeColor('#e2e8f0').lineWidth(1).moveTo(50, billToY).lineTo(doc.page.width - 50, billToY).stroke();
    
    // 3. Customer Info (Bill To)
    doc.y = billToY + 12;
    const custY = doc.y;
    doc.font('Helvetica-Bold').fontSize(10).fillColor('#2563eb').text('BILL TO (CUSTOMER)', 50, custY);
    doc.font('Helvetica-Bold').fontSize(11).fillColor('#1e293b').text(customer.name, 50, doc.y + 4);
    doc.font('Helvetica').fontSize(9).fillColor('#475569');
    if (customer.phone) doc.text(`Phone: ${customer.phone}`, 50, doc.y + 2);
    if (customer.address) doc.text(`Address: ${customer.address}`, 50, doc.y + 2);

    // 4. Billing Table Layout
    doc.y = Math.max(doc.y, custY + 65) + 15;
    const tableTop = doc.y;
    const col = { desc: 50, type: 260, amount: 420 };
    
    // Table Header Row
    doc.rect(50, tableTop, doc.page.width - 100, 20).fill('#f1f5f9');
    doc.fillColor('#475569').font('Helvetica-Bold').fontSize(9);
    doc.text('Description / Particulars', col.desc + 8, tableTop + 6);
    doc.text('Type', col.type + 8, tableTop + 6);
    doc.text('Amount (INR)', col.amount + 8, tableTop + 6);
    
    // Table Content Row
    const rowY = tableTop + 20;
    doc.strokeColor('#e2e8f0').lineWidth(1).rect(50, rowY, doc.page.width - 100, 32).stroke();
    doc.fillColor('#1e293b').font('Helvetica').fontSize(9.5);
    
    const descVal = transaction.description || (transaction.source === 'voice' ? transaction.transcript : 'Ledger Entry');
    doc.text(descVal.slice(0, 38), col.desc + 8, rowY + 11, { width: 200 });
    
    doc.font('Helvetica-Bold').fillColor(transaction.type === 'CREDIT' ? '#b91c1c' : '#0284c7');
    doc.text(transaction.type === 'CREDIT' ? 'Credit (Udhaar)' : 'Payment (Jama)', col.type + 8, rowY + 11);
    
    doc.font('Helvetica-Bold').fillColor('#1e293b');
    doc.text(formatINR(transaction.amount), col.amount + 8, rowY + 11);

    // 5. QR Code & Balance Summary Cards side-by-side
    doc.y = rowY + 60;
    const bottomY = doc.y;
    
    // Left Column: Payment UPI QR Code (120x120px bordered card)
    const qrPath = merchant.qrCodePath ? path.join(__dirname, '..', '..', merchant.qrCodePath) : null;
    if (qrPath && fs.existsSync(qrPath)) {
      doc.rect(50, bottomY, 150, 160).fill('#fafafa');
      doc.strokeColor('#e2e8f0').lineWidth(1).rect(50, bottomY, 150, 160).stroke();
      doc.image(qrPath, 65, bottomY + 15, { width: 120, height: 120 });
      doc.fillColor('#475569').font('Helvetica-Bold').fontSize(7.5).text('SCAN UPI QR TO PAY DIRECTLY', 50, bottomY + 142, { align: 'center', width: 150 });
    } else {
      doc.rect(50, bottomY, 150, 100).fill('#fafafa');
      doc.strokeColor('#e2e8f0').lineWidth(1).rect(50, bottomY, 150, 100).stroke();
      doc.fillColor('#94a3b8').font('Helvetica-Bold').fontSize(8).text('No UPI QR Code\nuploaded by Merchant.', 50, bottomY + 40, { align: 'center', width: 150 });
    }

    // Right Column: Summary block card
    const summaryX = 230;
    const summaryW = doc.page.width - 50 - summaryX; // 315 pt width
    doc.rect(summaryX, bottomY, summaryW, 100).fill('#f8fafc');
    doc.strokeColor('#e2e8f0').lineWidth(1).rect(summaryX, bottomY, summaryW, 100).stroke();
    
    let sumY = bottomY + 10;
    doc.fillColor('#64748b').font('Helvetica').fontSize(9).text('Previous Outstanding:', summaryX + 15, sumY);
    doc.fillColor('#1e293b').font('Helvetica-Bold').text(formatINR(transaction.balanceBefore), summaryX + 200, sumY);
    
    sumY += 22;
    const typeLabel = transaction.type === 'CREDIT' ? 'Credit Added (+):' : 'Payment Received (-):';
    const typeColor = transaction.type === 'CREDIT' ? '#b91c1c' : '#0284c7';
    doc.fillColor('#64748b').font('Helvetica').text(typeLabel, summaryX + 15, sumY);
    doc.fillColor(typeColor).font('Helvetica-Bold').text(`${transaction.type === 'CREDIT' ? '+' : '-'}${formatINR(transaction.amount)}`, summaryX + 200, sumY);

    sumY += 25;
    doc.strokeColor('#cbd5e1').lineWidth(1).moveTo(summaryX + 12, sumY).lineTo(summaryX + summaryW - 12, sumY).stroke();
    
    sumY += 8;
    doc.fillColor('#2563eb').font('Helvetica-Bold').fontSize(11).text('Net Outstanding:', summaryX + 15, sumY);
    doc.text(formatINR(transaction.balanceAfter), summaryX + 200, sumY);

    // 6. Signatory and Disclaimer Footer
    doc.y = bottomY + 185;
    doc.strokeColor('#e2e8f0').lineWidth(1).moveTo(50, doc.y).lineTo(doc.page.width - 50, doc.y).stroke();
    doc.y += 10;
    doc.fillColor('#94a3b8').font('Helvetica-Oblique').fontSize(8).text('This is a computer generated digital ledger invoice. No signature required.', 50, doc.y, { align: 'center' });

    drawFooter(doc);
    doc.end();

    stream.on('finish', () => resolve(filePath));
    stream.on('error', reject);
  });
}

/**
 * Generates an official customer statement report PDF covering a list of transactions.
 * Returns the absolute file path.
 */
async function generateStatementPDF({ merchant, customer, transactions, from, to }) {
  const fileName = `STATEMENT-${customer._id}-${Date.now()}.pdf`;
  const filePath = path.join(BILLS_DIR, fileName);

  const totalCredit = transactions.filter((t) => t.type === 'CREDIT').reduce((s, t) => s + t.amount, 0);
  const totalPayment = transactions.filter((t) => t.type === 'PAYMENT').reduce((s, t) => s + t.amount, 0);

  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 50 });
    const stream = fs.createWriteStream(filePath);
    doc.pipe(stream);

    drawHeader(doc, 'CUSTOMER LEDGER STATEMENT');

    // Merchant details & Customer details header
    const topY = doc.y;
    doc.font('Helvetica-Bold').fontSize(11).fillColor('#2563eb').text('MERCHANT LEDGER', 50, topY);
    doc.font('Helvetica-Bold').fontSize(11).fillColor('#2563eb').text('STATEMENT TO', 320, topY);
    doc.moveDown(0.4);

    let y = doc.y;
    doc.font('Helvetica').fontSize(10).fillColor('#111');
    doc.text(`${merchant.businessName}`, 50, y, { width: 240 });
    doc.text(`${customer.name}`, 320, y, { width: 220 });
    doc.text(`Proprietor: ${merchant.name}`, 50, doc.y, { width: 240 });
    y = doc.y;
    doc.text(`${customer.phone || '-'}`, 320, y - doc.currentLineHeight(), { width: 220 });
    doc.text(`Period: ${formatDate(from)} – ${formatDate(to)}`, 50, doc.y, { width: 240 });
    
    doc.moveDown(1.8);
    doc.strokeColor('#e2e8f0').lineWidth(1).moveTo(50, doc.y).lineTo(doc.page.width - 50, doc.y).stroke();
    doc.moveDown(1);

    // Table header
    const tableTop = doc.y;
    const col = { date: 50, type: 150, desc: 240, amount: 420 };
    doc.font('Helvetica-Bold').fontSize(10).fillColor('#fff');
    doc.rect(50, tableTop, doc.page.width - 100, 20).fill('#2563eb');
    doc.fillColor('#fff').text('Date', col.date + 8, tableTop + 5);
    doc.text('Type', col.type + 8, tableTop + 5);
    doc.text('Description / Particulars', col.desc + 8, tableTop + 5);
    doc.text('Amount (INR)', col.amount + 8, tableTop + 5);

    let rowY = tableTop + 24;
    doc.font('Helvetica').fontSize(9.5).fillColor('#111');

    transactions.forEach((t, idx) => {
      if (rowY > doc.page.height - 120) {
        doc.addPage();
        rowY = 50;
      }
      if (idx % 2 === 0) {
        doc.rect(50, rowY - 3, doc.page.width - 100, 18).fill('#f8fafc');
        doc.fillColor('#111');
      }
      doc.text(formatDate(t.createdAt), col.date + 8, rowY);
      doc.fillColor(t.type === 'CREDIT' ? '#b91c1c' : '#0284c7').text(t.type === 'CREDIT' ? 'Credit' : 'Payment', col.type + 8, rowY);
      doc.fillColor('#111').text((t.description || t.transcript || '-').slice(0, 26), col.desc + 8, rowY, { width: 160 });
      doc.text(`${t.type === 'CREDIT' ? '+' : '-'}${formatINR(t.amount)}`, col.amount + 8, rowY);
      rowY += 18;
    });

    // Check pagination height for summary card and QR Code
    doc.y = rowY + 20;
    const finalY = doc.y;
    if (finalY > doc.page.height - 200) {
      doc.addPage();
      doc.y = 50;
    }
    
    const blockY = doc.y;
    doc.strokeColor('#cbd5e1').lineWidth(1).moveTo(50, blockY).lineTo(doc.page.width - 50, blockY).stroke();
    
    const contentY = blockY + 15;
    
    // Left: QR Code Scanner Card
    const statementQrPath = merchant.qrCodePath ? path.join(__dirname, '..', '..', merchant.qrCodePath) : null;
    if (statementQrPath && fs.existsSync(statementQrPath)) {
      doc.rect(50, contentY, 150, 140).fill('#fafafa');
      doc.strokeColor('#e2e8f0').rect(50, contentY, 150, 140).stroke();
      doc.image(statementQrPath, 65, contentY + 10, { width: 120, height: 120 });
      doc.fillColor('#64748b').font('Helvetica-Bold').fontSize(7.5).text('SCAN UPI QR TO PAY OUTSTANDING', 50, contentY + 125, { align: 'center', width: 150 });
    } else {
      doc.rect(50, contentY, 150, 80).fill('#fafafa');
      doc.strokeColor('#e2e8f0').rect(50, contentY, 150, 80).stroke();
      doc.fillColor('#94a3b8').font('Helvetica-Bold').fontSize(8).text('No UPI QR Code\nuploaded by Merchant.', 50, contentY + 35, { align: 'center', width: 150 });
    }

    // Right: Summary Statistics Card
    const statX = 230;
    const statW = doc.page.width - 50 - statX; // 315 pt width
    doc.rect(statX, contentY, statW, 95).fill('#f8fafc');
    doc.strokeColor('#e2e8f0').rect(statX, contentY, statW, 95).stroke();
    
    let textY = contentY + 12;
    doc.fillColor('#64748b').font('Helvetica').fontSize(9.5).text('Total Outstanding Credit:', statX + 15, textY);
    doc.fillColor('#b91c1c').font('Helvetica-Bold').text(formatINR(totalCredit), statX + 200, textY);
    
    textY += 22;
    doc.fillColor('#64748b').font('Helvetica').text('Total Payments Received:', statX + 15, textY);
    doc.fillColor('#0284c7').font('Helvetica-Bold').text(formatINR(totalPayment), statX + 200, textY);

    textY += 24;
    doc.strokeColor('#cbd5e1').lineWidth(1).moveTo(statX + 12, textY).lineTo(statX + statW - 12, textY).stroke();
    
    textY += 8;
    doc.fillColor('#2563eb').font('Helvetica-Bold').fontSize(11.5).text('Net Ledger Balance:', statX + 15, textY);
    doc.text(formatINR(customer.currentBalance), statX + 200, textY);

    drawFooter(doc);
    doc.end();

    stream.on('finish', () => resolve(filePath));
    stream.on('error', reject);
  });
}

module.exports = { generateTransactionPDF, generateStatementPDF, formatINR, BILLS_DIR };
